services:
  postgres:
    env_file:
      - .env
    image: pgvector/pgvector:0.8.0-pg17
    container_name: solesonic-llm-api-db
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: solesonic-llm-api
      POSTGRES_DB: solesonic-llm-api
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_schema.sh:/docker-entrypoint-initdb.d/init_schema.sh
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solesonic-llm-api"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  postgres_data: