package com.solesonic.model.chat.attachment;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.ZonedDateTime;
import java.util.UUID;

@SuppressWarnings("unused")
@Entity
public class ChatAttachment {
    @Id
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    private UUID userId;

    private UUID chatId;

    private UUID chatMessageId;

    private String fileName;

    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Generated by the vision model, unlike {@link #description}, which the client supplies. Null
     * until the image has been described; the null is what makes describing it retryable.
     */
    @Column(columnDefinition = "TEXT")
    private String visionDescription;

    private String visionModel;

    /**
     * Why {@link #visionDescription} is still null. Set when a describe attempt fails, cleared when
     * one succeeds; both null means no attempt has been made yet.
     */
    @Enumerated(EnumType.STRING)
    private VisionFailureReason visionFailureReason;

    private String contentType;

    /**
     * How many vector store chunks this document was split into. Null until the extraction pass has
     * run, which is what makes indexing retryable on a later turn — the same idiom
     * {@link #visionDescription} uses for images. Always null for an image, which is described
     * rather than indexed.
     */
    private Integer chunkCount;

    /**
     * Why {@link #chunkCount} is still null. Set when an extraction attempt fails, cleared when one
     * succeeds; both null means no attempt has been made yet.
     */
    @Enumerated(EnumType.STRING)
    private ExtractionFailureReason extractionFailureReason;

    @JdbcTypeCode(SqlTypes.VARBINARY)
    private byte[] fileData;

    private long fileSizeBytes;

    private ZonedDateTime created;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public UUID getChatId() {
        return chatId;
    }

    public void setChatId(UUID chatId) {
        this.chatId = chatId;
    }

    public UUID getChatMessageId() {
        return chatMessageId;
    }

    public void setChatMessageId(UUID chatMessageId) {
        this.chatMessageId = chatMessageId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getVisionDescription() {
        return visionDescription;
    }

    public void setVisionDescription(String visionDescription) {
        this.visionDescription = visionDescription;
    }

    public String getVisionModel() {
        return visionModel;
    }

    public void setVisionModel(String visionModel) {
        this.visionModel = visionModel;
    }

    public VisionFailureReason getVisionFailureReason() {
        return visionFailureReason;
    }

    public void setVisionFailureReason(VisionFailureReason visionFailureReason) {
        this.visionFailureReason = visionFailureReason;
    }

    public Integer getChunkCount() {
        return chunkCount;
    }

    public void setChunkCount(Integer chunkCount) {
        this.chunkCount = chunkCount;
    }

    public ExtractionFailureReason getExtractionFailureReason() {
        return extractionFailureReason;
    }

    public void setExtractionFailureReason(ExtractionFailureReason extractionFailureReason) {
        this.extractionFailureReason = extractionFailureReason;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public byte[] getFileData() {
        return fileData;
    }

    public void setFileData(byte[] fileData) {
        this.fileData = fileData;
    }

    public long getFileSizeBytes() {
        return fileSizeBytes;
    }

    public void setFileSizeBytes(long fileSizeBytes) {
        this.fileSizeBytes = fileSizeBytes;
    }

    public ZonedDateTime getCreated() {
        return created;
    }

    public void setCreated(ZonedDateTime created) {
        this.created = created;
    }
}
