package com.solesonic.config.chat;

import com.solesonic.model.chat.history.ChatMessage;
import com.solesonic.service.image.GeneratedImageService;
import com.solesonic.service.ollama.ChatMessageService;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.NullMarked;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.MessageType;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.UUID;

@Component
public class DatabaseChatMemory implements ChatMemory {
    private static final Logger log = LoggerFactory.getLogger(DatabaseChatMemory.class);
    private final ChatMessageService chatMessageService;
    private final GeneratedImageService generatedImageService;

    public DatabaseChatMemory(ChatMessageService chatMessageService,
                              GeneratedImageService generatedImageService) {
        this.chatMessageService = chatMessageService;
        this.generatedImageService = generatedImageService;
    }

    private String sanitize(String text) {
        if (text == null) {
            return null;
        }

        String trimmed = text.trim();

        if (trimmed.isEmpty()) {
            return null;
        }

        return trimmed;
    }

    @Override
    public void add(@NonNull String conversationId, List<Message> messages) {
        log.debug("Adding messages to history.");

        UUID chatId = UUID.fromString(conversationId);

        for (Message message : messages) {
            // User messages are persisted by the caller before the stream starts, so that their id
            // is known up front. Saving them again here would duplicate every turn.
            if (message.getMessageType() == MessageType.USER) {
                continue;
            }

            String sanitizedText = sanitize(message.getText());

            if (sanitizedText == null) {
                continue;
            }

            ChatMessage chatMessage = new ChatMessage();
            chatMessage.setChatId(chatId);
            chatMessage.setMessageType(message.getMessageType());
            chatMessage.setMessage(sanitizedText);

            ChatMessage saved = chatMessageService.save(chatMessage);

            //An image generated by a tool during this turn exists before the turn's message does,
            //so it is stored unbound and claimed here. This is the only point where the assistant
            //message that produced it gets an id.
            if (message.getMessageType() == MessageType.ASSISTANT) {
                bindGeneratedImages(chatId, saved.getId());
            }
        }
    }

    /**
     * Bookkeeping, and bookkeeping must not cost the user their answer.
     * <p>
     * This runs inside the chat memory advisor, which runs inside the {@code ChatClient} call whose
     * response is the whole turn — so an exception escaping here does not just lose the link
     * between an image and its message, it discards a reply the model has already finished writing
     * and reports the turn as failed. The image itself is stored either way; what is lost is its
     * place in history, which is worth a log line and nothing more.
     */
    private void bindGeneratedImages(UUID chatId, UUID chatMessageId) {
        try {
            generatedImageService.bind(chatId, chatMessageId);
        } catch (RuntimeException runtimeException) {
            log.error("Could not attach generated images to chat message {}", chatMessageId, runtimeException);
        }
    }

    @Override
    @NullMarked
    public List<Message> get(String conversationId) {
        log.debug("Getting messages from history.");
        List<Message> messages = chatMessageService.findByChatId(UUID.fromString(conversationId));

        log.debug("Messages Found: {}", messages.size());
        return messages;
    }

    @Override
    @NullMarked
    public void clear(String conversationId) {
        //Leave as a no-op
        log.info("Clearing history.");
    }
}
